version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Specify your desired Python version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864899853618.dkr.ecr.ap-south-1.amazonaws.com
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  build:
    commands:
      - echo Tagging the Docker image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:latest
artifacts:
  files:
    - imagedefinitions.json # If deploying to ECS, this file is useful
  discard-paths: yes